# ------------------- General Options -------------------------
description                  : AB3DMOT
seed                         : 0

# --------------- main.py
save_root                    : ./results/KITTI
dataset                      : KITTI
split                        : val
det_name                     : pointrcnn
class_list                     : ['Car', 'Pedestrian', 'Cyclist']

score_threshold              : -10000
num_hypo                     : 1

# --------------- model.py
ego_com                      : false
vis                          : false
affi_pro                     : true

data_root                    : ./data/

dataset_path: "/mnt/nas3/Data/kitti-processed/object_tracking/training"
detections_path: "/mnt/nas3/Data/kitti-processed/object_tracking/data/pvrcnn/training"
save_path: '/home/eslim/workspace/Swift3DMOT/evaluation/det_results'
tracking_results_path: '/home/eslim/workspace/Swift3DMOT/evaluation/trk_results'
# val [1,6,8,10,12,13,14,15,16,18,19]
# trainval [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
# test [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
tracking_seqs: [1,6,8,10,12,13,14,15,16,18,19]
image_resolution: [1242,188]
mns_threshold : 0.5
tracking_type: "Car"
update_confidence: 0.5

state_func_covariance: 100
measure_func_covariance: 0.001
prediction_score_decay: 0.03
LiDAR_scanning_frequency: 10

max_prediction_num: 12
max_prediction_num_for_new_object: 2

# detection score threshold
input_score: 0
init_score: 2
update_score: 0
post_score: 0

# tracking latency (s)
# -1: global tracking
# 0.->500: online or near online tracking
latency: 0